### ISSUE TITLE
Can't seem to get it to work on CY8CKIT-043

### ISSUE THREAD

**Issue by AfdhalAtiffTan** [C47D/nRF24_Component#3]
My setup:
-1 board for TX
-1 board for RX
-Channel 63
-TX and RX address both 0x0123456789
-Arduino for debugging purposes.

According to the arduino_scanner output, the PSOC_TX is transmitting strongly at channel 63.
However, the PSOC_RX is not receiving anything.

Any tips? 

Update:
I just got it to run, apparently, I need to enable the auto-ack for it to work.

**Comment by C47D** [comment]
Hi,
In case you can't make it work, can you share the project bundle to check at the configurations?
I will try to reproduce to check why the component "doesn't work" with auto-ack disabled.

Carlos

**Comment by AfdhalAtiffTan** [comment]
It runs correctly now.
I think maybe it was caused my counterfeit nRF24L01+.

Thank you for your awesome library!

**Comment by C47D** [comment]
Thanks for the update, happy to know the component is useful, i will close the issue but don't hesitate on reporting any other problem.

I just found about the arduino_scanner project, i will try to implement it using this component and update it into the [nRF24 Example Projects repo](https://github.com/C47D/nRF24_Example_Projects).
